insert into public.topics (tier, section_number, name) values
  (1, 'Number'),
  (2, 'Algebra and graphs'),
  (3, 'Coordinate geometry'),
  (4, 'Geometry'),
  (5, 'Mensuration'),
  (6, 'Trigonometry'),
  (7, 'Transformations and vectors'),
  (8, 'Probability'),
  (9, 'Statistics')
on conflict (tier, section_number) do update set name = excluded.name;

insert into public.subtopics (topic_id, code, title, position)
select t.id, v.code, v.title, v.position
from (values
  (1, 'E1.1', 'Types of number', 1),
  (1, 'E1.2', 'Sets', 2),
  (1, 'E1.3', 'Powers and roots', 3),
  (1, 'E1.4', 'Fractions, decimals and percentages', 4),
  (1, 'E1.5', 'Ordering', 5),
  (1, 'E1.6', 'The four operations', 6),
  (1, 'E1.7', 'Indices I', 7),
  (1, 'E1.8', 'Standard form', 8),
  (1, 'E1.9', 'Estimation', 9),
  (1, 'E1.10', 'Limits of accuracy', 10),
  (1, 'E1.11', 'Ratio and proportion', 11),
  (1, 'E1.12', 'Rates', 12),
  (1, 'E1.13', 'Percentages', 13),
  (1, 'E1.14', 'Using a calculator', 14),
  (1, 'E1.15', 'Time', 15),
  (1, 'E1.16', 'Money', 16),
  (1, 'E1.17', 'Exponential growth and decay', 17),
  (1, 'E1.18', 'Surds', 18),
  (2, 'E2.1', 'Introduction to algebra', 1),
  (2, 'E2.2', 'Algebraic manipulation', 2),
  (2, 'E2.3', 'Algebraic fractions', 3),
  (2, 'E2.4', 'Indices II', 4),
  (2, 'E2.5', 'Equations', 5),
  (2, 'E2.6', 'Inequalities', 6),
  (2, 'E2.7', 'Sequences', 7),
  (2, 'E2.8', 'Proportion', 8),
  (2, 'E2.9', 'Graphs in practical situations', 9),
  (2, 'E2.10', 'Graphs of functions', 10),
  (2, 'E2.11', 'Sketching curves', 11),
  (2, 'E2.12', 'Differentiation', 12),
  (2, 'E2.13', 'Functions', 13),
  (3, 'E3.1', 'Coordinates', 1),
  (3, 'E3.2', 'Drawing linear graphs', 2),
  (3, 'E3.3', 'Gradient of linear graphs', 3),
  (3, 'E3.4', 'Length and midpoint', 4),
  (3, 'E3.5', 'Equations of linear graphs', 5),
  (3, 'E3.6', 'Parallel lines', 6),
  (3, 'E3.7', 'Perpendicular lines', 7),
  (4, 'E4.1', 'Geometrical terms', 1),
  (4, 'E4.2', 'Geometrical constructions', 2),
  (4, 'E4.3', 'Scale drawings', 3),
  (4, 'E4.4', 'Similarity', 4),
  (4, 'E4.5', 'Symmetry', 5),
  (4, 'E4.6', 'Angles', 6),
  (4, 'E4.7', 'Circle theorems I', 7),
  (4, 'E4.8', 'Circle theorems II', 8),
  (5, 'E5.1', 'Units of measure', 1),
  (5, 'E5.2', 'Area and perimeter', 2),
  (5, 'E5.3', 'Circles, arcs and sectors', 3),
  (5, 'E5.4', 'Surface area and volume', 4),
  (5, 'E5.5', 'Compound shapes and parts of shapes', 5),
  (6, 'E6.1', 'Pythagoras'' theorem', 1),
  (6, 'E6.2', 'Right-angled triangles', 2),
  (6, 'E6.3', 'Exact trigonometric values', 3),
  (6, 'E6.4', 'Trigonometric functions', 4),
  (6, 'E6.5', 'Non-right-angled triangles', 5),
  (6, 'E6.6', 'Pythagoras'' theorem and trigonometry', 6),
  (7, 'E7.1', 'Transformations', 1),
  (7, 'E7.2', 'Vectors in two dimensions', 2),
  (7, 'E7.3', 'Magnitude of a vector', 3),
  (7, 'E7.4', 'Vector geometry', 4),
  (8, 'E8.1', 'Introduction to probability', 1),
  (8, 'E8.2', 'Relative and expected frequencies', 2),
  (8, 'E8.3', 'Probability of combined events', 3),
  (8, 'E8.4', 'Conditional probability', 4),
  (9, 'E9.1', 'Classifying statistical data', 1),
  (9, 'E9.2', 'Interpreting statistical data', 2),
  (9, 'E9.3', 'Averages and measures of spread', 3),
  (9, 'E9.4', 'Statistical charts and diagrams', 4),
  (9, 'E9.5', 'Scatter diagrams', 5),
  (9, 'E9.6', 'Cumulative frequency diagrams', 6),
  (9, 'E9.7', 'Histograms', 7)
) as v(section_number, code, title, position)
join public.topics t
  on t.section_number = v.section_number and t.tier = 'extended'
on conflict (code) do update
  set title = excluded.title, position = excluded.position, topic_id = excluded.topic_id;
